; ╔══════════════════════════════════════════════════════════════╗
; ║              BPSync — PlatformIO Configuration              ║
; ╠══════════════════════════════════════════════════════════════╣
; ║  Kullanım:                                                  ║
; ║    pio run -e wrist_module              → sadece derle      ║
; ║    pio run -e wrist_module -t upload    → derle + yükle     ║
; ║    pio device monitor                   → Serial Monitor    ║
; ╚══════════════════════════════════════════════════════════════╝

[platformio]
default_envs = wrist_module
build_dir     = .pio/build
libdeps_dir   = .pio/libdeps
src_dir       = firmware/wrist_module

[env:wrist_module]
platform  = nordicnrf52
framework = arduino
board     = adafruit_feather_nrf52840
monitor_speed   = 115200
monitor_filters = default, time
lib_deps =
    sparkfun/SparkFun MAX3010x Pulse and Proximity Sensor Library
    electroniccats/MPU6050
    adafruit/Adafruit MCP9808 Library
    adafruit/Adafruit BusIO

; [env:chest_module]
; platform  = nordicnrf52
; framework = arduino
; board     = seeed_xiao_nrf52840
; monitor_speed = 115200
; lib_deps  = (aynısı)
